import React from "react";
import { MDBDataTable, MDBTable } from "mdbreact";

const btn= () => <button className="btn btn-primary">Add</button>; 
const ExistingTutorsPage = () => {
  const data = {
    columns: [
      {
        label: "Tutor Id",
        field: "id",
        sort: "asc",
        width: 120,
      },
      {
        label: "Username",
        field: "username",
        sort: "asc",
        width: 270,
      },
      {
        label: "First Name",
        field: "first_name",
        sort: "asc",
        width: 150,
      },
      {
        label: "Last Name",
        field: "last_name",
        sort: "asc",
        width: 200,
      },
      {
        label: "Contact No",
        field: "contact_no",
        sort: "asc",
        width: 100,
      },
      {
        label: "Gender",
        field: "gender",
        sort: "asc",
        width: 100,
      },
      {
        label: "Action",
        field: "removeBtn",
        sort: "asc",
        width: 100,
      },
      
    ],
    rows: [
      {
        id: "212223334",
        username: "akelshaw1@unblog.fr",
        first_name: "Ravindranath",
        last_name: "Batadombalena",
        contact_no: "4728332341",
        gender: "Female",
        removeBtn:<button className="btn btn-primary">Remove</button>,
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },

      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },

      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },

      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },

      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },

      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aldin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
      {
        id: "2",
        username: "akelshaw1@unblog.fr",
        first_name: "Aladin",
        last_name: "Kelshaw",
        contact_no: "4728332341",
        gender: "Male",
      },
    ],
  };

  return (
    <MDBDataTable
      className="text-center"
      theaderColor="#011250"
      tbodyColor="secondary-color"
      searching={true}
      data={data}
      hover
      noBottomColumns
    />
  );
};

export default ExistingTutorsPage;

