# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - learnx

on:
  push:
    branches:
      - server_release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://learnx.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_82c23dad8b9c469aae9e23d68f634598 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f1b0f41ec2174050bb15ee91f5f9a221 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: learnx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_82c23dad8b9c469aae9e23d68f634598 }}/learnx_server:${{ github.sha }}
        file: ./server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'learnx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f8113fbf69946ec8a9bacccc868bca9 }}
        images: 'learnx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_82c23dad8b9c469aae9e23d68f634598 }}/learnx_server:${{ github.sha }}'
